# Generated by Django 4.0.4 on 2022-04-16 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('hours_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percent', models.FloatField()),
                ('law_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=70)),
                ('session_number', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betting_time', models.DateTimeField(auto_now_add=True)),
                ('current_amount', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='session.session')),
            ],
        ),
    ]
