# Generated by Django 4.0.4 on 2022-04-16 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=models.Model, related_name='user_sessions', to='session.session')),
                ('user', models.ForeignKey(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
