# Generated by Django 4.0.4 on 2022-04-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_data', to='session.session'),
        ),
    ]
