# Generated by Django 4.0.4 on 2022-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_sessiondata_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='limit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='limit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='robot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='law_number',
            field=models.IntegerField(choices=[(44, '44 ФЗ'), (223, '223 ФЗ')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'активна'), ('complete', 'проведена'), ('fall', 'не состоялась'), ('deleted', 'снята с публикации')], max_length=10),
        ),
    ]
