# Generated by Django 4.0.4 on 2022-04-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_rename_limit_time_usersession_notification_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='limit_price',
            new_name='notification_price',
        ),
    ]
