# Generated by Django 4.0.4 on 2022-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_rename_limit_price_usersession_notification_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='notification_price',
            new_name='limit_price',
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='notification_time',
            new_name='limit_time',
        ),
    ]
