# Generated by Django 4.0.4 on 2022-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_rename_notification_price_usersession_limit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
